package com.tabariyya.dtogenerator.idea;

import com.intellij.lang.annotation.HighlightSeverity;
import com.intellij.codeInsight.daemon.impl.HighlightInfo;
import com.intellij.testFramework.fixtures.LightJavaCodeInsightFixtureTestCase;
import java.util.List;

public class FieldPathAnnotatorTest extends LightJavaCodeInsightFixtureTestCase {

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        myFixture.addClass("package com.tabariyya.dtogenerator.fields; public @interface Fields {}");
        myFixture.addClass("package com.tabariyya.dtogenerator.fields;"
                + " @java.lang.annotation.Target(java.lang.annotation.ElementType.METHOD)"
                + " public @interface FieldPath { Class<?> value() default Object.class;"
                + " boolean returnType() default false; }");
        myFixture.addClass("package a; @com.tabariyya.dtogenerator.fields.Fields public class User { private String username; }");
        myFixture.addClass("package a; @com.tabariyya.dtogenerator.fields.Fields public class Account { private String iban; }");
        myFixture.addClass("package a; @com.tabariyya.dtogenerator.fields.Fields public class Admin extends User { private String role; }");
        myFixture.addClass("package a; @java.lang.annotation.Target({java.lang.annotation.ElementType.TYPE,"
                + " java.lang.annotation.ElementType.PARAMETER, java.lang.annotation.ElementType.LOCAL_VARIABLE,"
                + " java.lang.annotation.ElementType.METHOD}) public @interface DtoConfig {"
                + " @com.tabariyya.dtogenerator.fields.FieldPath String[] fields() default {};"
                + " @com.tabariyya.dtogenerator.fields.FieldPath(User.class) String[] userFields() default {};"
                + " @com.tabariyya.dtogenerator.fields.FieldPath(Admin.class) String[] adminFields() default {};"
                + " @com.tabariyya.dtogenerator.fields.FieldPath(returnType = true) String[] ownFields() default {}; }");
    }

    public void testAcceptsAFieldOfTheExpectedOwner() {
        assertEquals(List.of(), errorsIn("@DtoConfig(userFields = {User.USERNAME}) class C {}"));
    }

    public void testAcceptsAnyOwnerWhenUnrestricted() {
        assertEquals(List.of(), errorsIn("@DtoConfig(fields = {User.USERNAME, Account.IBAN}) class C {}"));
    }

    public void testRejectsAFieldOfAnotherOwner() {
        assertEquals(
                List.of("a.Account#iban is a field of a.Account, but only fields of a.User are allowed here"),
                errorsIn("@DtoConfig(userFields = {Account.IBAN}) class C {}"));
    }

    public void testRejectsAStringThatIsNotAField() {
        assertEquals(
                List.of("\"totally.made.up\" does not refer to a field; use a constant generated by @Fields"),
                errorsIn("@DtoConfig(fields = {\"totally.made.up\"}) class C {}"));
    }

    public void testRejectsASupertypesOwnConstant() {
        assertEquals(
                List.of("a.User#username is a field of a.User, but only fields of a.Admin are allowed here"),
                errorsIn("@DtoConfig(adminFields = {User.USERNAME}) class C {}"));
    }

    public void testAcceptsAnInheritedFieldThroughTheSubclassOwnConstant() {
        assertEquals(List.of(), errorsIn("@DtoConfig(adminFields = {Admin.USERNAME, Admin.ROLE}) class C {}"));
    }

    public void testRejectsASubtypeFieldInASupertypeMember() {
        assertEquals(
                List.of("a.Admin#role is a field of a.Admin, but only fields of a.User are allowed here"),
                errorsIn("@DtoConfig(userFields = {Admin.ROLE}) class C {}"));
    }

    public void testFlagsAPathInsideANestedAnnotation() {
        myFixture.addClass("package a; public @interface Wrapper { DtoConfig inner(); }");

        assertEquals(
                List.of("\"totally.made.up\" does not refer to a field; use a constant generated by @Fields"),
                errorsIn("@Wrapper(inner = @DtoConfig(fields = {\"totally.made.up\"})) class C {}"));
    }

    public void testFlagsAPathOnAParameter() {
        assertEquals(
                List.of("\"totally.made.up\" does not refer to a field; use a constant generated by @Fields"),
                errorsIn("class C { void m(@DtoConfig(fields = {\"totally.made.up\"}) int p) {} }"));
    }

    public void testFlagsAPathOnALocalVariable() {
        assertEquals(
                List.of("\"totally.made.up\" does not refer to a field; use a constant generated by @Fields"),
                errorsIn("class C { void m() { @DtoConfig(fields = {\"totally.made.up\"}) int v = 0; } }"));
    }

    public void testFlagsFieldPathOnANonStringMember() {
        assertEquals(
                List.of("@FieldPath is only supported on String and String[], not int[]"),
                errorsIn("@interface BadCfg { @com.tabariyya.dtogenerator.fields.FieldPath int[] fields(); }"));
    }

    public void testFlagsFieldPathOutsideAnAnnotation() {
        assertEquals(
                List.of("@FieldPath is only supported on annotation members"),
                errorsIn("class C { @com.tabariyya.dtogenerator.fields.FieldPath String m() { return \"\"; } }"));
    }

    public void testAcceptsAFieldOfTheAnnotatedMethodsReturnType() {
        assertEquals(
                List.of(),
                errorsIn("class C { @DtoConfig(ownFields = {User.USERNAME}) User user() { return null; } }"));
    }

    public void testRejectsAFieldOfAnotherClassThanTheReturnType() {
        assertEquals(
                List.of("a.Account#iban is a field of a.Account, but only fields of a.User are allowed here"),
                errorsIn("class C { @DtoConfig(ownFields = {Account.IBAN}) User user() { return null; } }"));
    }

    public void testTheSameMemberFollowsWhicheverReturnTypeItIsUsedOn() {
        assertEquals(
                List.of(),
                errorsIn("class C {"
                        + " @DtoConfig(ownFields = {User.USERNAME}) User user() { return null; }"
                        + " @DtoConfig(ownFields = {Account.IBAN}) Account account() { return null; } }"));
    }

    public void testRejectsReturnTypeModeWhereThereIsNoReturnType() {
        assertEquals(
                List.of("@FieldPath(returnType = true) on ownFields requires the annotation to be applied"
                        + " to a method, whose return type names the expected class"),
                errorsIn("@DtoConfig(ownFields = {User.USERNAME}) class C {}"));
    }

    public void testRejectsReturnTypeModeOnAReturnTypeThatIsNotAClass() {
        assertEquals(
                List.of("@FieldPath(returnType = true) on ownFields cannot be checked against the return"
                        + " type void, which is not a class"),
                errorsIn("class C { @DtoConfig(ownFields = {User.USERNAME}) void nothing() {} }"));
    }

    public void testRejectsNamingAnOwnerTwice() {
        assertEquals(
                List.of("@FieldPath takes either a class or returnType = true, not both"),
                errorsIn("@interface BadCfg { @com.tabariyya.dtogenerator.fields.FieldPath("
                        + "value = User.class, returnType = true) String[] both(); }"));
    }

    private List<String> errorsIn(String declaration) {
        myFixture.configureByText("C.java", "package a;\n" + declaration);
        return myFixture.doHighlighting(HighlightSeverity.ERROR).stream()
                .map(HighlightInfo::getDescription)
                .filter(FieldPathAnnotatorTest::isFieldPathProblem)
                .toList();
    }

    private static boolean isFieldPathProblem(String description) {
        return description != null
                && (description.contains("does not refer to a field")
                        || description.contains("are allowed here")
                        || description.contains("is only supported on")
                        || description.contains("requires the annotation to be applied")
                        || description.contains("cannot be checked against the return type")
                        || description.contains("not both"));
    }
}
