package com.tabariyya.dtogenerator.fields;

import java.util.List;

/**
 * The naming rule, the path format and every diagnostic message, in one place.
 *
 * <p>The annotation processor and the IntelliJ plugin both compile against this class, so a field
 * resolves to the same constant name and the same path in the compiler and in the editor. Anything
 * either side needs to agree on belongs here rather than in one of them.
 */
public final class FieldConstants {

    /** Separates the owning class from the field name in a path. */
    public static final char SEPARATOR = '#';

    public static final String ANNOTATION = "com.tabariyya.dtogenerator.fields.Fields";

    public static final String FIELD_PATH_ANNOTATION = "com.tabariyya.dtogenerator.fields.FieldPath";

    private FieldConstants() {}

    /**
     * The constant name for a field: {@code UPPER_SNAKE_CASE}, breaking a word only where an
     * uppercase run actually ends, so {@code userID} gives {@code USER_ID} and {@code htmlURLParser}
     * gives {@code HTML_URL_PARSER}.
     */
    public static String nameFor(String fieldName) {
        StringBuilder constant = new StringBuilder(fieldName.length() + 4);
        for (int i = 0; i < fieldName.length(); i++) {
            char character = fieldName.charAt(i);
            if (startsWord(fieldName, i) && constant.length() != 0 && constant.charAt(constant.length() - 1) != '_') {
                constant.append('_');
            }
            constant.append(Character.toUpperCase(character));
        }
        return constant.toString();
    }

    private static boolean startsWord(String fieldName, int index) {
        if (index == 0 || !Character.isUpperCase(fieldName.charAt(index))) {
            return false;
        }
        if (!Character.isUpperCase(fieldName.charAt(index - 1))) {
            return true;
        }
        return index + 1 < fieldName.length() && Character.isLowerCase(fieldName.charAt(index + 1));
    }

    /** Whether the field's own name is already what {@link #nameFor} would produce. */
    public static boolean namesItsOwnConstant(String fieldName) {
        return nameFor(fieldName).equals(fieldName);
    }

    /** Whether the supertype walk should stop here rather than harvest a JDK class's fields. */
    public static boolean isJdkType(String qualifiedName) {
        return qualifiedName != null
                && (qualifiedName.startsWith("java.")
                        || qualifiedName.startsWith("javax.")
                        || qualifiedName.startsWith("jdk."));
    }

    public static String valueFor(String qualifiedClassName, String fieldName) {
        return qualifiedClassName + SEPARATOR + fieldName;
    }

    public static String ownerOf(String path) {
        int separator = path.indexOf(SEPARATOR);
        return separator < 0 ? "" : path.substring(0, separator);
    }

    public static String fieldNameOf(String path) {
        return path.substring(path.indexOf(SEPARATOR) + 1);
    }

    public static String notAFieldMessage(String path) {
        return "\"" + path + "\" does not refer to a field; use a constant generated by @Fields";
    }

    public static String wrongOwnerMessage(String path, String owner, String expectedOwner) {
        return path + " is a field of " + owner + ", but only fields of " + expectedOwner + " are allowed here";
    }

    public static String nameIsAlreadyConstantMessage(String fieldName) {
        return "no constant is generated for field " + fieldName + ": its name is already in constant form";
    }

    public static String nameTakenMessage(String constantName, String fieldName) {
        return "no constant is generated for field " + fieldName + ": " + constantName
                + " is already a field of this class";
    }

    public static String collisionMessage(String constantName, List<String> fieldNames) {
        return "no constant is generated for " + constantName + ": fields " + join(fieldNames) + " all map to it";
    }

    /** The javac packages injection needs, in the order they are usually written. */
    public static final String[] REQUIRED_EXPORTS = {
        "jdk.compiler/com.sun.tools.javac.code",
        "jdk.compiler/com.sun.tools.javac.processing",
        "jdk.compiler/com.sun.tools.javac.tree",
        "jdk.compiler/com.sun.tools.javac.util",
    };

    /**
     * Names the flags as JVM arguments rather than compiler options on purpose. The processor runs
     * inside the compiler's JVM, so only that JVM's module graph decides what it can reach — and
     * javac rejects a plain {@code add-exports} compiler option outright when the target is 8.
     */
    public static String injectionUnavailableMessage(String reason) {
        StringBuilder flags = new StringBuilder();
        for (String export : REQUIRED_EXPORTS) {
            flags.append("\n  -J--add-exports=").append(export).append("=ALL-UNNAMED");
        }
        return "@Fields generated nothing: this compiler does not allow the syntax tree access it needs ("
                + reason + "). Fork the compiler that builds the annotated class and pass it these JVM"
                + " arguments — they are JVM arguments, not compiler options:" + flags;
    }

    public static String notSupportedOnInterfacesMessage() {
        return "@Fields is not supported on interfaces, which cannot declare instance fields";
    }

    public static String notSupportedOnEnumsMessage() {
        return "@Fields is not supported on enums";
    }

    public static String notAnAnnotationMemberMessage() {
        return "@FieldPath is only supported on annotation members";
    }

    public static String unsupportedTypeMessage(String type) {
        return "@FieldPath is only supported on String and String[], not " + type;
    }

    public static String conflictingOwnerMessage() {
        return "@FieldPath takes either a class or returnType = true, not both";
    }

    public static String notOnAMethodMessage(String member) {
        return "@FieldPath(returnType = true) on " + member
                + " requires the annotation to be applied to a method, whose return type names the expected class";
    }

    public static String unusableReturnTypeMessage(String member, String returnType) {
        return "@FieldPath(returnType = true) on " + member + " cannot be checked against the return type "
                + returnType + ", which is not a class";
    }

    /** {@code String.join} is fine on 8, but this keeps the message identical to the plugin's. */
    private static String join(List<String> values) {
        StringBuilder joined = new StringBuilder();
        for (String value : values) {
            if (joined.length() != 0) {
                joined.append(", ");
            }
            joined.append(value);
        }
        return joined.toString();
    }
}
